improve git-review

diff --git a/git-review b/git-review
--- a/git-review
+++ b/git-review
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -lt 2 ]; then
-    echo "Usage: $0 rev-list [options]...";
+    echo "Usage: $0 rev-list reviewer summary [options]...";
     echo
     exit 1
 fi
@@ -25,10 +25,16 @@ else
   fi
 fi
 
+remote_url=$(
+  git remote -v | egrep -o 'CDH/[a-zA-Z]+.git' | head -1)
+if [ -z "$remote_url" ]; then
+  echo 'could not figure out remote URL from remotes!'
+  exit 1
+fi
 
 post-review --description="$DESCRIPTION" \
   --target-groups=platform \
   --target-people="$REVIEWER" \
   --diff-filename=<($DIFF_CMD) \
-  --repository-url=git://github.sf.cloudera.com/CDH/hadoop.git \
+  --repository-url=git://github.sf.cloudera.com/$remote_url \
   --summary="$SUMMARY"
